### ISSUE TITLE
Block gen too fast and Feature Request

### ISSUE THREAD

**Issue by QBGamer** [quangpao/OreGenerator#2]
Block appeared almost immediately when you put lava and water close together
![image](https://user-images.githubusercontent.com/118107525/201519252-28893f91-8c0f-4130-b10c-4782255d2faf.png)

Can you add block to mix with water, like water with anvil... In nether you cant place water there so I think you should make lava with other too and add what block will appear in what dimension!

This plugin is great.
Thanks for reading this!

**Comment by quangpao** [comment]
- [ ] Block generating too fast.
