### ISSUE TITLE
[F] (more suggestions)

### ISSUE THREAD

**Issue by Zarkness2** [quangpao/OreGenerator#6]
#### _**Your feature request is related to a problem? Please describe it.
> It is not related to any bug, my suggestions are as follows.

1 - add support for older versions.

2 - add placeholders. 

3 - add support for different skyblock plugins such as Bentobox, SuperiorSkyblock2, etc...

4 - add support for jetsminions.

5 - add the possibility for the plugin to work only in x biomes.

6 - add support for basalt generator.

in short it would be to add the options that the other plugins of this style have such as https://www.spigotmc.org/resources/customcobblegen-now-supports-basalt-generators-1-13-1-16.70736/ 
https://www.spigotmc.org/resources/customoregen.9532/
https://www.spigotmc.org/resources/%E2%9C%85-advancedoregen-%E2%9B%8F%EF%B8%8F-random-ores-for-skyblock%EF%B8%8F-%E2%9C%A8.40527/

#### _**Describe the solution you would like**_ (A clear and concise description of the problem.
> I already put it in the previous one

#### _****Describe the alternatives you have considered**_ > (A clear and concise description of what you want to happen).
> (A clear and concise description of the alternative solutions or features you have considered). 

#### _****Additional context (optional)**_ > (Add any additional context here).
> (Add here any other context or screenshots about the feature request).

#### ***Image (Optional)***_ > (Upload the image here).
> (Upload image here)

**Comment by quangpao** [comment]
There is a big problem with my plugin logic so it will take time to remake the whole plugin to support the Skyblock plugins. I also have to prepare for my interview in the following days so this whole things will take a lot of time too.

**Comment by Zarkness2** [comment]
ok no problem, it's not something that needs to be right now, when you can add it and you're done.

**Comment by Zarkness2** [comment]
hello any news?

**Comment by quangpao** [comment]
no, not yet
